name: End-to-End Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-validation:
    name: End-to-End Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install xmllint
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils
    
    - name: Extract version from POM
      id: version
      run: |
        POM_FILE="src/mcpagent/pom.xml"
        CURRENT_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" "$POM_FILE")
        VERSION_NUMBER=${CURRENT_VERSION%-SNAPSHOT}
        echo "version=$VERSION_NUMBER" >> $GITHUB_OUTPUT
        echo "full_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION (testing: $VERSION_NUMBER)"
    
    - name: Validate services
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        PLATFORM="${{ matrix.platform }}"
        echo "Validating services on $PLATFORM..."
        
        # Use the validation script
        chmod +x scripts/docker/validate-services.sh
        ./scripts/docker/validate-services.sh "$VERSION" "$PLATFORM"
